package ia.app.ltia.viewcontroller.health;

import ia.app.ltia.LifeTrackerConstants;
import ia.app.ltia.LifeTrackerHelper;
import ia.app.ltia.model.Database;
import ia.app.ltia.viewcontroller.FrameDragListener;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDialog;

/**
 *
 * @author
 */
public class AddExerciseViewController extends javax.swing.JDialog {

    private boolean parentMustReloadExercises = false;
    private boolean isValidCalories = false;
    private boolean isValidMinutes = false;
    
    /**
     * Creates new form AddExerciseViewController
     */
    public AddExerciseViewController(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initUndecoratedFrame();
        initComponentsCustomStyling();        
        
    }
    
    private void initUndecoratedFrame(){
        
        //To remove title, must set undecorated to true.
        //But dont do that in here, it must be in initComponents so 
        //you must do it in the JFrame properties.
        //this.setUndecorated(true);
        
        //Drag the window from by selecting any part of the frame        
        
        FrameDragListener frameDragListener = new FrameDragListener((java.awt.Window)this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);        

        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        
        /*
        this.setLayout(new BorderLayout());
        */
        
        /*
        //((JComponent)this.getContentPane()).setBorder(new LineBorder(Color.BLACK));                
        logger.debug("Layout = " + this.getLayout().toString());        
        TitlePane titlePane = new TitlePane();        
        logger.debug("Adding titlePane");
        this.add(titlePane, BorderLayout.NORTH);               
        */        
        
    }    
    
    private void initComponentsCustomStyling() {
        
        //jFrame background
        this.getContentPane().setBackground(LifeTrackerConstants.GUI_BACKGROUND_COLOR_2);
               
        //Set background on all fields
        this.jTextFieldExerciseName.setBackground(LifeTrackerConstants.GUI_FIELD_BACKGROUND_COLOR_2);
        this.jTextFieldCaloriesBurned.setBackground(LifeTrackerConstants.GUI_FIELD_BACKGROUND_COLOR_2);
        this.jTextFieldDurationMinutes.setBackground(LifeTrackerConstants.GUI_FIELD_BACKGROUND_COLOR_2);

        this.jTextFieldExerciseName.setBorder(BorderFactory.createEmptyBorder());
        this.jTextFieldCaloriesBurned.setBorder(BorderFactory.createEmptyBorder());
        this.jTextFieldDurationMinutes.setBorder(BorderFactory.createEmptyBorder());
        
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);        
    }      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldExerciseName = new javax.swing.JTextField();
        jTextFieldCaloriesBurned = new javax.swing.JTextField();
        jTextFieldDurationMinutes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        validCalories = new javax.swing.JLabel();
        validMinutes = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Exercise Name");

        jLabel2.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Calories burned");

        jLabel3.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("per");

        jLabel4.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("minutes");

        jTextFieldExerciseName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldExerciseName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldExerciseNameKeyReleased(evt);
            }
        });

        jTextFieldCaloriesBurned.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldCaloriesBurned.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCaloriesBurnedKeyReleased(evt);
            }
        });

        jTextFieldDurationMinutes.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldDurationMinutes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDurationMinutesKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelStatus.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        validCalories.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N

        validMinutes.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add New Exercise");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldExerciseName)
                                .addComponent(jSeparator1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldCaloriesBurned, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(validCalories, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextFieldDurationMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(validMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldExerciseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCaloriesBurned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(validCalories, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldDurationMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(validMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String exerciseName = jTextFieldExerciseName.getText();
        String caloriesBurned = jTextFieldCaloriesBurned.getText();
        String durationInMinutes = jTextFieldDurationMinutes.getText();
        
        if( LifeTrackerHelper.isValidString(exerciseName) &&
            LifeTrackerHelper.isValidDouble(caloriesBurned) && 
            LifeTrackerHelper.isValidDouble(durationInMinutes) ) {
            
            //if we are inside here, it means we have valid data and can save the exercise
            Database db = new Database(LifeTrackerConstants.DATABASE_NAME);
            db.addNewExercise(exerciseName, Double.parseDouble(caloriesBurned), Double.parseDouble(durationInMinutes));
                    
            //Because we saved a new exercise, we need to re-load the exercises in the parent window
            parentMustReloadExercises = true;            
            
            //Empty the JTextFields
            jTextFieldExerciseName.setText("");
            jTextFieldCaloriesBurned.setText("");
            jTextFieldDurationMinutes.setText("");
            
            //And set the status to show the exercise was added            
            jLabelStatus.setText("New exercise " + exerciseName + " added!");
            jLabelStatus.setForeground(Color.BLACK);
            jLabelStatus.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.TICK_ICON)));
        }
        else {
            //invalid data found
            jLabelStatus.setText("Invalid data. Please correct and re-try.");
            jLabelStatus.setForeground(Color.RED);
            jLabelStatus.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.CROSS_ICON)));
            
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldExerciseNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldExerciseNameKeyReleased
    }//GEN-LAST:event_jTextFieldExerciseNameKeyReleased

    private void jTextFieldCaloriesBurnedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCaloriesBurnedKeyReleased
        String checkInt = jTextFieldCaloriesBurned.getText(); 
        
        jLabelStatus.setText("");
        jLabelStatus.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));

        if(LifeTrackerHelper.checkNumber(checkInt)){
            isValidCalories = true;
            validCalories.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.TICK_ICON)));
        }
        else{
            isValidCalories = false;
            if(jTextFieldCaloriesBurned.getText().trim().isEmpty()){
                validCalories.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));
            }
            else{
                validCalories.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.CROSS_ICON)));
            }
        }                 
    }//GEN-LAST:event_jTextFieldCaloriesBurnedKeyReleased

    private void jTextFieldDurationMinutesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDurationMinutesKeyReleased
        String checkInt = jTextFieldDurationMinutes.getText(); 
        
        jLabelStatus.setText("");
        jLabelStatus.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));

        if(LifeTrackerHelper.checkNumber(checkInt)){
            isValidMinutes = true;
            validMinutes.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.TICK_ICON)));
        }
        else{
            isValidMinutes = false;
            if(jTextFieldDurationMinutes.getText().trim().isEmpty()){
                validMinutes.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));
            }
            else{
                validMinutes.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.CROSS_ICON)));
            }
        }                 
    }//GEN-LAST:event_jTextFieldDurationMinutesKeyReleased
    
    public boolean getParentMustReloadExercises() {
        return parentMustReloadExercises;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddExerciseViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddExerciseViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddExerciseViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddExerciseViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddExerciseViewController dialog = new AddExerciseViewController(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldCaloriesBurned;
    private javax.swing.JTextField jTextFieldDurationMinutes;
    private javax.swing.JTextField jTextFieldExerciseName;
    private javax.swing.JLabel validCalories;
    private javax.swing.JLabel validMinutes;
    // End of variables declaration//GEN-END:variables
}
