package ia.app.ltia.viewcontroller.member;

import ia.app.ltia.LifeTrackerConstants;
import ia.app.ltia.LifeTrackerHelper;
import ia.app.ltia.model.Member;
import ia.app.ltia.viewcontroller.FrameDragListener;
import ia.app.ltia.viewcontroller.HomeViewController;
import java.awt.event.WindowEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author
 */
public class NewMemberViewController extends javax.swing.JFrame {
     
    private String password;
    String name;
    String hashedPassword;
    String email;
    boolean isValidPassword = false;
    boolean isValidEmail = false;
    boolean isValidName = false;

    public NewMemberViewController() {
        initComponents();
        initUndecoratedFrame();
        initComponentsCustomStyling();        
    }
    
    private void initComponentsCustomStyling() {        
        //jFrame background
        this.getContentPane().setBackground(LifeTrackerConstants.GUI_BACKGROUND_COLOR_2);
        this.NAMEPANEL.setBackground(LifeTrackerConstants.GUI_BACKGROUND_COLOR_2);
        
        //Top panel background
        this.jTopPanel.setBackground(LifeTrackerConstants.GUI_COLOR_3);
        
        //Text field backgrounds        
        this.jTextFieldPassword.setBackground(LifeTrackerConstants.GUI_FIELD_BACKGROUND_COLOR_2);
        this.jTextFieldPassword.setBorder(BorderFactory.createEmptyBorder());                
        this.jTextFieldName.setBackground(LifeTrackerConstants.GUI_FIELD_BACKGROUND_COLOR_2);
        this.jTextFieldName.setBorder(BorderFactory.createEmptyBorder());                
        this.jTextFieldEmail.setBackground(LifeTrackerConstants.GUI_FIELD_BACKGROUND_COLOR_2);
        this.jTextFieldEmail.setBorder(BorderFactory.createEmptyBorder());                        
        
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);        
    }
    
    private void initUndecoratedFrame(){
        
        //To remove title, must set undecorated to true.
        //But dont do that in here, it must be in initComponents so 
        //you must do it in the JFrame properties.
        //this.setUndecorated(true);
        
        //Drag the window from by selecting any part of the frame
        FrameDragListener frameDragListener = new FrameDragListener((java.awt.Window)this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NAMEPANEL = new javax.swing.JPanel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        CANCELNEWMEMBER = new javax.swing.JButton();
        SUBMITNEWMEMBER = new javax.swing.JButton();
        NAMELINE = new javax.swing.JSeparator();
        EMAILLINE = new javax.swing.JSeparator();
        jTopPanel = new javax.swing.JPanel();
        jButtonCloseScreen = new javax.swing.JButton();
        jTitleLabel = new javax.swing.JLabel();
        NAMELINE1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        INFOMEMBER = new javax.swing.JLabel();
        validPassword = new javax.swing.JLabel();
        validName = new javax.swing.JLabel();
        validEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1333, 824));

        NAMEPANEL.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldName.setBackground(new java.awt.Color(255, 251, 223));
        jTextFieldName.setFont(new java.awt.Font("Keep Calm Med", 1, 36)); // NOI18N
        jTextFieldName.setBorder(null);
        jTextFieldName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextFieldNameMouseMoved(evt);
            }
        });
        jTextFieldName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldNameMouseExited(evt);
            }
        });
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Keep Calm Med", 0, 30)); // NOI18N
        jLabel2.setText("Name");

        jLabel1.setFont(new java.awt.Font("Keep Calm Med", 0, 30)); // NOI18N
        jLabel1.setText("Password");

        jTextFieldPassword.setBackground(new java.awt.Color(255, 251, 223));
        jTextFieldPassword.setFont(new java.awt.Font("Keep Calm Med", 1, 36)); // NOI18N
        jTextFieldPassword.setBorder(null);
        jTextFieldPassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTextFieldPasswordMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextFieldPasswordMouseMoved(evt);
            }
        });
        jTextFieldPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldPasswordMouseExited(evt);
            }
        });
        jTextFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordActionPerformed(evt);
            }
        });
        jTextFieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPasswordKeyReleased(evt);
            }
        });

        jTextFieldEmail.setBackground(new java.awt.Color(255, 251, 223));
        jTextFieldEmail.setFont(new java.awt.Font("Keep Calm Med", 1, 36)); // NOI18N
        jTextFieldEmail.setBorder(null);
        jTextFieldEmail.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextFieldEmailMouseMoved(evt);
            }
        });
        jTextFieldEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldEmailMouseEntered(evt);
            }
        });
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyReleased(evt);
            }
        });

        CANCELNEWMEMBER.setBackground(new java.awt.Color(247, 53, 53));
        CANCELNEWMEMBER.setFont(new java.awt.Font("Keep Calm Med", 1, 24)); // NOI18N
        CANCELNEWMEMBER.setText("Cancel");
        CANCELNEWMEMBER.setBorder(null);
        CANCELNEWMEMBER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELNEWMEMBERActionPerformed(evt);
            }
        });

        SUBMITNEWMEMBER.setBackground(new java.awt.Color(117, 238, 77));
        SUBMITNEWMEMBER.setFont(new java.awt.Font("Keep Calm Med", 1, 24)); // NOI18N
        SUBMITNEWMEMBER.setText("Submit");
        SUBMITNEWMEMBER.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SUBMITNEWMEMBER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITNEWMEMBERActionPerformed(evt);
            }
        });

        NAMELINE.setBackground(new java.awt.Color(0, 0, 0));

        EMAILLINE.setBackground(new java.awt.Color(0, 0, 0));

        jTopPanel.setBackground(new java.awt.Color(204, 204, 204));

        jButtonCloseScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ia/app/ltia/images/exit-icon2-normal.png"))); // NOI18N
        jButtonCloseScreen.setAlignmentY(0.0F);
        jButtonCloseScreen.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 8, 12));
        jButtonCloseScreen.setBorderPainted(false);
        jButtonCloseScreen.setContentAreaFilled(false);
        jButtonCloseScreen.setFocusPainted(false);
        jButtonCloseScreen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonCloseScreen.setIconTextGap(0);
        jButtonCloseScreen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonCloseScreen.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ia/app/ltia/images/exit-icon-highlighted.png"))); // NOI18N
        jButtonCloseScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseScreenMouseClicked(evt);
            }
        });
        jButtonCloseScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseScreenActionPerformed(evt);
            }
        });

        jTitleLabel.setFont(new java.awt.Font("Keep Calm Med", 1, 60)); // NOI18N
        jTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        jTitleLabel.setText("Create A New Member");

        javax.swing.GroupLayout jTopPanelLayout = new javax.swing.GroupLayout(jTopPanel);
        jTopPanel.setLayout(jTopPanelLayout);
        jTopPanelLayout.setHorizontalGroup(
            jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCloseScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jTopPanelLayout.setVerticalGroup(
            jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCloseScreen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTopPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jTitleLabel)
                .addGap(22, 22, 22))
        );

        NAMELINE1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Keep Calm Med", 0, 30)); // NOI18N
        jLabel4.setText("Email");

        INFOMEMBER.setBackground(new java.awt.Color(255, 251, 223));
        INFOMEMBER.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        INFOMEMBER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        validPassword.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N

        validName.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N

        validEmail.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N

        javax.swing.GroupLayout NAMEPANELLayout = new javax.swing.GroupLayout(NAMEPANEL);
        NAMEPANEL.setLayout(NAMEPANELLayout);
        NAMEPANELLayout.setHorizontalGroup(
            NAMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NAMEPANELLayout.createSequentialGroup()
                .addGroup(NAMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NAMEPANELLayout.createSequentialGroup()
                        .addGap(931, 931, 931)
                        .addComponent(SUBMITNEWMEMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(CANCELNEWMEMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NAMEPANELLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(NAMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(INFOMEMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(NAMEPANELLayout.createSequentialGroup()
                                .addGroup(NAMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(NAMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NAMELINE)
                                    .addComponent(jTextFieldName)
                                    .addComponent(NAMELINE1)
                                    .addComponent(jTextFieldPassword)
                                    .addComponent(EMAILLINE)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(NAMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(validPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        NAMEPANELLayout.setVerticalGroup(
            NAMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NAMEPANELLayout.createSequentialGroup()
                .addComponent(jTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(NAMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NAMEPANELLayout.createSequentialGroup()
                        .addGroup(NAMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NAMEPANELLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(validName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NAMELINE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addGroup(NAMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NAMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NAMEPANELLayout.createSequentialGroup()
                                .addComponent(NAMELINE1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(validEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NAMEPANELLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel4)))
                .addGap(11, 11, 11)
                .addComponent(EMAILLINE, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(INFOMEMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(NAMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CANCELNEWMEMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SUBMITNEWMEMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NAMEPANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NAMEPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseScreenActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButtonCloseScreenActionPerformed

    private void jButtonCloseScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseScreenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCloseScreenMouseClicked

    private void SUBMITNEWMEMBERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITNEWMEMBERActionPerformed
        // TODO add your handling code here:

        name = jTextFieldName.getText();
        password = jTextFieldPassword.getText();
        email = jTextFieldEmail.getText();
        if(LifeTrackerHelper.checkPassword(password) && password.length()>=8 && LifeTrackerHelper.checkName(name) && LifeTrackerHelper.checkEmail(email)){

            // At this point, we are good to create a new Member inside Database class will be called to
            // insert the new member details into the database

            //we must hash the password first because we don't want to save it as raw password
            hashedPassword = BCrypt.hashpw(password, BCrypt.gensalt());
            Member newMember = new Member(name, hashedPassword, email, true);

            //Go to the next screen but ...
            NewMemberDetailsViewController form2 = new NewMemberDetailsViewController();

            //... make it aware of the new member by calling it's setMember method
            form2.setMember(newMember);
            form2.setVisible(true);
            this.dispose();
        }
        else {
            if(LifeTrackerHelper.checkPassword(password) && password.length()>=8 && LifeTrackerHelper.checkName(name)){
                INFOMEMBER.setText("Invalid Email, Please Try Again");
                //set relative text underlined red to signify whcih aspects are needed correction (and below)
            }
            else if(LifeTrackerHelper.checkPassword(password) && password.length()>=8){
                INFOMEMBER.setText("Invalid Name & Email, Please Try Again");
            }
            else if(LifeTrackerHelper.checkName(name) && LifeTrackerHelper.checkEmail(email)){
                INFOMEMBER.setText("Invalid Password, Please Try Again");
            }
            else if(LifeTrackerHelper.checkName(name)){
                INFOMEMBER.setText("Invalid Email & Password, Please Try Again");
            }
            else if(LifeTrackerHelper.checkEmail(email)){
                INFOMEMBER.setText("Invalid Name & Password, Please Try Again");
            }
            else {
                INFOMEMBER.setText("All Fields Are Invalid, Please Try Again");
            }
        }

    }//GEN-LAST:event_SUBMITNEWMEMBERActionPerformed

    private void CANCELNEWMEMBERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELNEWMEMBERActionPerformed
        this.dispose();
        HomeViewController form3 = new HomeViewController();
        form3.setVisible(true);
    }//GEN-LAST:event_CANCELNEWMEMBERActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldEmailMouseEntered
        INFOMEMBER.setText("Enter your most preferred email address, as we will be sending emails to you!");
    }//GEN-LAST:event_jTextFieldEmailMouseEntered

    private void jTextFieldEmailMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldEmailMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailMouseMoved

    private void jTextFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordActionPerformed

    private void jTextFieldPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPasswordMouseExited
        // TODO add your handling code here:
        INFOMEMBER.setText("");
    }//GEN-LAST:event_jTextFieldPasswordMouseExited

    private void jTextFieldPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPasswordMouseEntered
        // TODO add your handling code here:
        INFOMEMBER.setText("Password must Contain at Least 1 Lowercase and Uppercase Letter, 1 Number and be at Least 8 Characters");
    }//GEN-LAST:event_jTextFieldPasswordMouseEntered

    private void jTextFieldPasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPasswordMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordMouseMoved

    private void jTextFieldPasswordMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPasswordMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordMouseDragged

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNameMouseExited
        INFOMEMBER.setText("");
    }//GEN-LAST:event_jTextFieldNameMouseExited

    private void jTextFieldNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNameMouseEntered
        INFOMEMBER.setText("Enter your First Name");
    }//GEN-LAST:event_jTextFieldNameMouseEntered

    private void jTextFieldNameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNameMouseMoved
        
    }//GEN-LAST:event_jTextFieldNameMouseMoved

    private void jTextFieldPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPasswordKeyReleased
        String checkPassword = jTextFieldPassword.getText();

        if(LifeTrackerHelper.checkPassword(checkPassword)){
            isValidPassword = true;
            validPassword.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.TICK_ICON)));
        }
        else{
            isValidPassword = false;
            if(jTextFieldPassword.getText().trim().isEmpty()){
                validPassword.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));
            }
            else{
                validPassword.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.CROSS_ICON)));
            }
        }
    }//GEN-LAST:event_jTextFieldPasswordKeyReleased

    private void jTextFieldEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyReleased
        String checkEmail = jTextFieldEmail.getText();

        if(LifeTrackerHelper.checkEmail(checkEmail)){
            isValidEmail = true;
            validEmail.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.TICK_ICON)));
        }
        else{
            isValidEmail = false;
            if(jTextFieldEmail.getText().trim().isEmpty()){
                validEmail.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));
            }
            else{
                validEmail.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.CROSS_ICON)));
            }
        }
    }//GEN-LAST:event_jTextFieldEmailKeyReleased

    private void jTextFieldNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyReleased
        String checkName = jTextFieldName.getText();

        if(LifeTrackerHelper.checkName(checkName)){
            isValidName = true;
            validName.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.TICK_ICON)));
        }
        else{
            isValidName = false;
            if(jTextFieldName.getText().trim().isEmpty()){
                validName.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));
            }
            else{
                validName.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.CROSS_ICON)));
            }
        }        
    }//GEN-LAST:event_jTextFieldNameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMemberViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMemberViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMemberViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMemberViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMemberViewController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCELNEWMEMBER;
    private javax.swing.JSeparator EMAILLINE;
    private javax.swing.JLabel INFOMEMBER;
    private javax.swing.JSeparator NAMELINE;
    private javax.swing.JSeparator NAMELINE1;
    private javax.swing.JPanel NAMEPANEL;
    private javax.swing.JButton SUBMITNEWMEMBER;
    private javax.swing.JButton jButtonCloseScreen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JLabel jTitleLabel;
    private javax.swing.JPanel jTopPanel;
    private javax.swing.JLabel validEmail;
    private javax.swing.JLabel validName;
    private javax.swing.JLabel validPassword;
    // End of variables declaration//GEN-END:variables
}
