SELECT ME.DATE AS "EVENTDATE", ME.MEALID AS "EVENTID", M.Long_Name AS "EVENTNAME", ME.CALORIESGAINED AS "CALORIES"
FROM MEALEVENT ME, FOOD M
WHERE M.ID = ME.MEALID
UNION
SELECT EE.DATE, EE.EXERCISEID, E.EXERCISENAME, EE.CALORIESBURNED * -1
FROM EXERCISEEVENT EE, EXERCISE E
WHERE E.ID = EE.EXERCISEID
ORDER BY 1 DESC