package ia.app.ltia.viewcontroller.meal;

import ia.app.ltia.LifeTrackerConstants;
import ia.app.ltia.LifeTrackerHelper;
import ia.app.ltia.model.Database;
import ia.app.ltia.viewcontroller.FrameDragListener;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDialog;

/**
 *
 * @author
 */
public class AddMealViewController extends javax.swing.JDialog {
    
    private boolean parentMustReloadMeals = false;
    private boolean isValidProtein = false;
    private boolean isValidCarbs = false;
    private boolean isValidFat = false;
    private boolean isValidFiber = false;
    private boolean isValidEnergy = false;
    private boolean isValidServing = false;

    /**
     * Creates new form AddMealViewController
     */
    public AddMealViewController(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initUndecoratedFrame();
        initComponentsCustomStyling();        
    }
    
    public boolean getParentMustReloadExercises() {
        return parentMustReloadMeals;
    }  
    
    private void initUndecoratedFrame(){
        
        //To remove title, must set undecorated to true.
        //But dont do that in here, it must be in initComponents so 
        //you must do it in the JFrame properties.
        //this.setUndecorated(true);
        
        //Drag the window from by selecting any part of the frame        
        
        FrameDragListener frameDragListener = new FrameDragListener((java.awt.Window)this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);        

        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        
        /*
        this.setLayout(new BorderLayout());
        */
        
        /*
        //((JComponent)this.getContentPane()).setBorder(new LineBorder(Color.BLACK));                
        logger.debug("Layout = " + this.getLayout().toString());        
        TitlePane titlePane = new TitlePane();        
        logger.debug("Adding titlePane");
        this.add(titlePane, BorderLayout.NORTH);               
        */        
        
    }    
    
    private void initComponentsCustomStyling() {
        
        //jFrame background
        this.getContentPane().setBackground(LifeTrackerConstants.GUI_BACKGROUND_COLOR_2);
               
        //Set background on all fields
        this.jTextFieldCalories.setBackground(LifeTrackerConstants.GUI_FIELD_BACKGROUND_COLOR_2);
        this.jTextFieldCarbs.setBackground(LifeTrackerConstants.GUI_FIELD_BACKGROUND_COLOR_2);
        this.jTextFieldFat.setBackground(LifeTrackerConstants.GUI_FIELD_BACKGROUND_COLOR_2);
        this.jTextFieldFiber.setBackground(LifeTrackerConstants.GUI_FIELD_BACKGROUND_COLOR_2);
        this.jTextFieldMealDescription.setBackground(LifeTrackerConstants.GUI_FIELD_BACKGROUND_COLOR_2);
        this.jTextFieldProtein.setBackground(LifeTrackerConstants.GUI_FIELD_BACKGROUND_COLOR_2);
        this.jTextFieldServingSize.setBackground(LifeTrackerConstants.GUI_FIELD_BACKGROUND_COLOR_2);

        this.jTextFieldCalories.setBorder(BorderFactory.createEmptyBorder());
        this.jTextFieldCarbs.setBorder(BorderFactory.createEmptyBorder());
        this.jTextFieldFat.setBorder(BorderFactory.createEmptyBorder());
        this.jTextFieldFiber.setBorder(BorderFactory.createEmptyBorder());
        this.jTextFieldMealDescription.setBorder(BorderFactory.createEmptyBorder());
        this.jTextFieldProtein.setBorder(BorderFactory.createEmptyBorder());
        this.jTextFieldServingSize.setBorder(BorderFactory.createEmptyBorder());
        
        //buttons
        jButtonSave.setBackground(LifeTrackerConstants.GUI_BUTTON_COLOR);
        jButton2.setBackground(LifeTrackerConstants.GUI_BUTTON_COLOR);
        
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldMealDescription = new javax.swing.JTextField();
        jTextFieldProtein = new javax.swing.JTextField();
        jTextFieldCarbs = new javax.swing.JTextField();
        jTextFieldFiber = new javax.swing.JTextField();
        jTextFieldFat = new javax.swing.JTextField();
        jTextFieldCalories = new javax.swing.JTextField();
        jTextFieldServingSize = new javax.swing.JTextField();
        jComboBoxServingSizeUnit = new javax.swing.JComboBox<>();
        jButtonSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        validFiber = new javax.swing.JLabel();
        validProtein = new javax.swing.JLabel();
        validEnergy = new javax.swing.JLabel();
        validCarbs = new javax.swing.JLabel();
        validServingSize = new javax.swing.JLabel();
        validFat = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Meal description");

        jLabel2.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Carbs (g)");

        jLabel3.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Protein (g)");

        jLabel4.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fiber (g)");

        jLabel5.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Fat (g)");

        jLabel6.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Energy (Calories)");

        jLabel7.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Serving size");

        jTextFieldMealDescription.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldMealDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMealDescriptionActionPerformed(evt);
            }
        });

        jTextFieldProtein.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldProtein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProteinActionPerformed(evt);
            }
        });
        jTextFieldProtein.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldProteinKeyReleased(evt);
            }
        });

        jTextFieldCarbs.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldCarbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCarbsActionPerformed(evt);
            }
        });
        jTextFieldCarbs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCarbsKeyReleased(evt);
            }
        });

        jTextFieldFiber.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldFiber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFiberActionPerformed(evt);
            }
        });
        jTextFieldFiber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFiberKeyReleased(evt);
            }
        });

        jTextFieldFat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldFat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFatActionPerformed(evt);
            }
        });
        jTextFieldFat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFatKeyReleased(evt);
            }
        });

        jTextFieldCalories.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldCalories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCaloriesActionPerformed(evt);
            }
        });
        jTextFieldCalories.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCaloriesKeyReleased(evt);
            }
        });

        jTextFieldServingSize.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldServingSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldServingSizeActionPerformed(evt);
            }
        });
        jTextFieldServingSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldServingSizeKeyReleased(evt);
            }
        });

        jComboBoxServingSizeUnit.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jComboBoxServingSizeUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "ml" }));

        jButtonSave.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Keep Calm Med", 0, 12)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelStatus.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N

        validFiber.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N

        validProtein.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N

        validEnergy.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N

        validCarbs.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N

        validServingSize.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N

        validFat.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Keep Calm Med", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Add New Meal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSave)
                                .addGap(29, 29, 29)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldMealDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                    .addComponent(jSeparator1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldProtein, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(validProtein, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCarbs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(validCarbs, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldFiber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(validFiber, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldFat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validFat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCalories, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldServingSize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxServingSizeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validServingSize, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButtonSave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldMealDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validProtein, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCarbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validCarbs, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextFieldFiber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(validFiber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(validFat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldFat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCalories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldServingSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxServingSizeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(validServingSize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButtonSave});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProteinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProteinActionPerformed

    private void jTextFieldCarbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCarbsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCarbsActionPerformed

    private void jTextFieldFiberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFiberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFiberActionPerformed

    private void jTextFieldFatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFatActionPerformed

    private void jTextFieldCaloriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCaloriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCaloriesActionPerformed

    private void jTextFieldServingSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldServingSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldServingSizeActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
        String mealDescription = jTextFieldMealDescription.getText();
        String proteinAsString = jTextFieldProtein.getText();
        String carbsAsString = jTextFieldCarbs.getText();
        String fiberAsString = jTextFieldFiber.getText();
        String fatAsString = jTextFieldFat.getText();
        String caloriesAsString = jTextFieldCalories.getText();
        String servingSizeAsString = jTextFieldServingSize.getText();
        
        if( LifeTrackerHelper.isValidString(mealDescription) &&
            LifeTrackerHelper.isValidDouble(proteinAsString) &&
            LifeTrackerHelper.isValidDouble(carbsAsString) &&
            LifeTrackerHelper.isValidDouble(fiberAsString) &&
            LifeTrackerHelper.isValidDouble(fatAsString) &&
            LifeTrackerHelper.isValidDouble(caloriesAsString) &&
            LifeTrackerHelper.isValidDouble(servingSizeAsString)) {

            String servingSizeUnit = jComboBoxServingSizeUnit.getSelectedItem().toString();
            
            Database db = new Database(LifeTrackerConstants.DATABASE_NAME);
            if(db.addNewMeal(mealDescription, Double.parseDouble(proteinAsString), Double.parseDouble(carbsAsString),
                    Double.parseDouble(fiberAsString), Double.parseDouble(fatAsString), Double.parseDouble(caloriesAsString),
                    Double.parseDouble(servingSizeAsString), servingSizeUnit)){
                
                //Because we saved a new meal, we need to re-load the meals in the parent window
                parentMustReloadMeals = true;     
                
                jLabelStatus.setText("Meal was saved!");
                jLabelStatus.setForeground(Color.BLACK);
                jLabelStatus.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.TICK_ICON)));
                
            }
            else {
                jLabelStatus.setText(LifeTrackerConstants.DATABASE_ERROR_MESSAGE);
                jLabelStatus.setForeground(Color.RED);
                jLabelStatus.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.CROSS_ICON)));
            }
        }                 
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldMealDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMealDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMealDescriptionActionPerformed

    private void jTextFieldProteinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProteinKeyReleased
        String checkInt = jTextFieldProtein.getText();
        
        jLabelStatus.setText("");
        jLabelStatus.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));             

        if(LifeTrackerHelper.checkNumber(checkInt)){
            isValidProtein = true;
            validProtein.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.TICK_ICON)));
        }
        else{
            isValidProtein = false;
            if(jTextFieldProtein.getText().trim().isEmpty()){
                validProtein.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));
            }
            else{
                validProtein.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.CROSS_ICON)));
            }
        }
    }//GEN-LAST:event_jTextFieldProteinKeyReleased

    private void jTextFieldCarbsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCarbsKeyReleased
        String checkInt = jTextFieldCarbs.getText();
        
        jLabelStatus.setText("");
        jLabelStatus.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));        

        if(LifeTrackerHelper.checkNumber(checkInt)){
            isValidCarbs = true;
            validCarbs.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.TICK_ICON)));
        }
        else{
            isValidCarbs = false;
            if(jTextFieldCarbs.getText().trim().isEmpty()){
                validCarbs.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));
            }
            else{
                validCarbs.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.CROSS_ICON)));
            }
        }        
    }//GEN-LAST:event_jTextFieldCarbsKeyReleased

    private void jTextFieldFiberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFiberKeyReleased
        String checkInt = jTextFieldFiber.getText();
        
        jLabelStatus.setText("");
        jLabelStatus.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));        

        if(LifeTrackerHelper.checkNumber(checkInt)){
            isValidFiber = true;
            validFiber.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.TICK_ICON)));
        }
        else{
            isValidFiber = false;
            if(jTextFieldFiber.getText().trim().isEmpty()){
                validFiber.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));
            }
            else{
                validFiber.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.CROSS_ICON)));
            }
        }  
    }//GEN-LAST:event_jTextFieldFiberKeyReleased

    private void jTextFieldFatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFatKeyReleased
        String checkInt = jTextFieldFat.getText();
        
        jLabelStatus.setText("");
        jLabelStatus.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));        

        if(LifeTrackerHelper.checkNumber(checkInt)){
            isValidFat = true;
            validFat.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.TICK_ICON)));
        }
        else{
            isValidFat = false;
            if(jTextFieldFat.getText().trim().isEmpty()){
                validFat.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));
            }
            else{
                validFat.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.CROSS_ICON)));
            }
        }         
    }//GEN-LAST:event_jTextFieldFatKeyReleased

    private void jTextFieldCaloriesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCaloriesKeyReleased
        String checkInt = jTextFieldCalories.getText();
        
        jLabelStatus.setText("");
        jLabelStatus.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));

        if(LifeTrackerHelper.checkNumber(checkInt)){
            isValidEnergy = true;
            validEnergy.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.TICK_ICON)));
        }
        else{
            isValidEnergy = false;
            if(jTextFieldCalories.getText().trim().isEmpty()){
                validEnergy.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));
            }
            else{
                validEnergy.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.CROSS_ICON)));
            }
        }                 
    }//GEN-LAST:event_jTextFieldCaloriesKeyReleased

    private void jTextFieldServingSizeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldServingSizeKeyReleased
        String checkInt = jTextFieldServingSize.getText();
        
        jLabelStatus.setText("");
        jLabelStatus.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));        

        if(LifeTrackerHelper.checkNumber(checkInt)){
            isValidServing = true;
            validServingSize.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.TICK_ICON)));
        }
        else{
            isValidServing = false;
            if(jTextFieldServingSize.getText().trim().isEmpty()){
                validServingSize.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.EMPTY_ICON)));
            }
            else{
                validServingSize.setIcon(new ImageIcon(getClass().getResource(LifeTrackerConstants.CROSS_ICON)));
            }
        }        
    }//GEN-LAST:event_jTextFieldServingSizeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMealViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMealViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMealViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMealViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddMealViewController dialog = new AddMealViewController(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxServingSizeUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextFieldCalories;
    private javax.swing.JTextField jTextFieldCarbs;
    private javax.swing.JTextField jTextFieldFat;
    private javax.swing.JTextField jTextFieldFiber;
    private javax.swing.JTextField jTextFieldMealDescription;
    private javax.swing.JTextField jTextFieldProtein;
    private javax.swing.JTextField jTextFieldServingSize;
    private javax.swing.JLabel validCarbs;
    private javax.swing.JLabel validEnergy;
    private javax.swing.JLabel validFat;
    private javax.swing.JLabel validFiber;
    private javax.swing.JLabel validProtein;
    private javax.swing.JLabel validServingSize;
    // End of variables declaration//GEN-END:variables
}